### ISSUE TITLE
Feature: greeter-test.ts 模板测试文件 add waffle matcher

### ISSUE THREAD

**Issue by chrischenubc** [WhiteMatrixTech/solidity-hardhat-seed#6]
### Description
`greeter-test.ts` 如果是作为模板测试文件的话， 这儿可能有一个小问题

https://github.com/WhiteMatrixTech/solidity-hardhat-seed/blob/25f0f54eccdcc36630c4d2df07626558de54e48c/packages/contracts/test/greeter-test.ts#L1-L4
这里面chai好像并没有使用waffle matcher, 导致一些contract functions 返回BigNumber的时候test, 导致chai match BigNumber报错

### Proposed solution

* 可以考虑在这里加上一行
https://github.com/WhiteMatrixTech/solidity-hardhat-seed/blob/25f0f54eccdcc36630c4d2df07626558de54e48c/packages/contracts/test/upgradeable/greeter-upgradeable-test.ts#L10

* 或者也可以考虑直接使用hardhat的一个`@nomiclabs/hardhat-waffle`的插件，默认使用了waffle matcher
https://hardhat.org/guides/waffle-testing.html

**Comment by Lucklyric** [comment]
这个其实不算模板，只是starter seed。这个测试里没有涉及到 number所以没有加。不过你说的第二个方案感觉更通用。你测试看看是不是 加了后 都不需要   chai.use(solidity); 如果是的话，可以提一个PR。

**Comment by Lucklyric** [comment]
`Also, you don't need to call chai.use. This initialization is already handled by @nomiclabs/hardhat-waffle. Just be sure to include require("@nomiclabs/hardhat-waffle"); in your Hardhat config.` 看样子是的，那这个就很方便了。

**Comment by chrischenubc** [comment]
> 这个其实不算模板，只是starter seed。这个测试里没有涉及到 number所以没有加。不过你说的第二个方案感觉更通用。你测试看看是不是 加了后 都不需要 chai.use(solidity); 如果是的话，可以提一个PR。

恩呢， 我之前测试过， 确实不需要加chai.use(solidity)了

**Comment by Lucklyric** [comment]
我提了一个PR可以看一下
